db = {}
db["3uPEKAnMP82ukt4dpbIeiV_apcad_apgid"] = {}
db["3uPEKAnMP82ukt4dpbIeiV_apcad_apgid"]["Name"] = "BYY"
db["3uPEKAnMP82ukt4dpbIeiV_apcad_apgid"]["Remark"] = "skm's Project."
db["20vUWwo99BUfpgOPd7G01K_apcad_apgid"] = {}
db["20vUWwo99BUfpgOPd7G01K_apcad_apgid"]["Name"] = "JKT - XS"
db["20vUWwo99BUfpgOPd7G01K_apcad_apgid"]["Remark"] = "skm's Project."
db["1fo61ItUrCwvmll_yEdAhJ_apcad_apgid"] = {}
db["1fo61ItUrCwvmll_yEdAhJ_apcad_apgid"]["Name"] = "apcad - pub"
db["1fo61ItUrCwvmll_yEdAhJ_apcad_apgid"]["Remark"] = "skm's Project."
db["1YRPaNmPzB1OeTXb6mpZGL_apcad_apgid"] = {}
db["1YRPaNmPzB1OeTXb6mpZGL_apcad_apgid"]["Name"] = "Little"
db["1YRPaNmPzB1OeTXb6mpZGL_apcad_apgid"]["Remark"] = "skm's Project."
db["1T0cXKBTrCrh5b$oeJSqdT_apcad_apgid"] = {}
db["1T0cXKBTrCrh5b$oeJSqdT_apcad_apgid"]["Name"] = "SCF MB Expansion"
db["1T0cXKBTrCrh5b$oeJSqdT_apcad_apgid"]["Remark"] = "skm's Project."
db["23Q_sxufr1_Pl1N_91bD06_apcad_apgid"] = {}
db["23Q_sxufr1_Pl1N_91bD06_apcad_apgid"]["Name"] = "JKT - XXS"
db["23Q_sxufr1_Pl1N_91bD06_apcad_apgid"]["Remark"] = "skm's Project."
db["3sarapWob8oBcUSxKDFSmY_apcad_apgid"] = {}
db["3sarapWob8oBcUSxKDFSmY_apcad_apgid"]["Name"] = "brain"
db["3sarapWob8oBcUSxKDFSmY_apcad_apgid"]["Remark"] = "skm's Project."
db["3URJ3aYDv6vuXwL9ttVz6z_apcad_apgid"] = {}
db["3URJ3aYDv6vuXwL9ttVz6z_apcad_apgid"]["Name"] = "Test-1x1x1"
db["3URJ3aYDv6vuXwL9ttVz6z_apcad_apgid"]["Remark"] = "skm's Project."
db["3eQnX5_Wf1$POPsMKgYLGr_apcad_apgid"] = {}
db["3eQnX5_Wf1$POPsMKgYLGr_apcad_apgid"]["Name"] = "Test-5x3x7"
db["3eQnX5_Wf1$POPsMKgYLGr_apcad_apgid"]["Remark"] = "skm's Project."
db["1DgZyvyBT5kvsrrIrXOX2__apcad_apgid"] = {}
db["1DgZyvyBT5kvsrrIrXOX2__apcad_apgid"]["Name"] = "JKT - S"
db["1DgZyvyBT5kvsrrIrXOX2__apcad_apgid"]["Remark"] = "skm's Project."
db["0WotuN5m17WfnuvO8TsQHr_apcad_apgid"] = {}
db["0WotuN5m17WfnuvO8TsQHr_apcad_apgid"]["Name"] = "Test-1x1x2"
db["0WotuN5m17WfnuvO8TsQHr_apcad_apgid"]["Remark"] = "skm's Project."
